# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redditbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'word',
            },
        ),
        migrations.CreateModel(
            name='Wordtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='wordtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redditbot.Wordtype'),
        ),
    ]
